version: "3.7"
services:
  db:
    image: postgres
    restart: always
    networks:
      - my_network
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - pgdata:/var/lib/postgresql/data

  
  Server:
    image: serv/server
    restart: always
    networks:
      - my_network
    container_name: server
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - my_network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - db
      
networks:
  my_network:
    driver: bridge

volumes:
  pgdata:


